config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'events#index'
  resources :users, only: %i[edit update]
  
  
  resources :top, only: :index
  resources :events
  resources :diary
  resources :tasks
  resources :targets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_target.rb
class DailyTarget < ApplicationRecord
  belongs_to :user

  validates :date_id, uniqueness: true

end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/monthly_target.rb
class MonthlyTarget < ApplicationRecord
  belongs_to :user

  validates :month_id, uniqueness: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true


  has_many :tasks, dependent: :destroy
  has_many :monthly_target
  has_many :weekly_target
  has_many :daily_target
end

app/models/user_target.rb
class UserTarget

  include ActiveModel::Model
  attr_accessor :monthly_content, :weekly_content, :daily_content, :user_id, :date_id, :week_id, :month_id

# ここにバリデーションの処理を書く

  def save
    # 各テーブルにデータを保存する処理を書く
    MonthlyTarget.create(monthly_content: monthly_content, user_id: user_id, month_id: month_id)
    WeeklyTarget.create(weekly_content: weekly_content, user_id: user_id, week_id: week_id)
    DailyTarget.create(daily_content: daily_content, user_id: user_id, date_id: date_id)
  end
end

app/models/weekly_target.rb
class WeeklyTarget < ApplicationRecord
  belongs_to :user

  validates :week_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_events_diaries
  
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_events_diaries
    @index_events = Event.where('start_time >= ?', Date.today).order('start_time ASC').limit(5)
    @index_diaries = Diary.where('start_time <= ?', Date.today).order('start_time ASC').limit(5)
    end
end

app/controllers/diary_controller.rb
class DiaryController < ApplicationController
  def index
    @diaries = Diary.where(user_id: current_user.id)
    @diary = Diary.new
  end

  def new
    @diary = Diary.new
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def create
    Diary.create(diary_parameter)
    redirect_to diary_index_path
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to diary_index_path, notice: '削除しました'
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_parameter)
      redirect_to diary_index_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def diary_parameter
    params.require(:diary).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = Event.where(user_id: current_user.id)
    @event = Event.new
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_url, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private


  def set_event
    @event = Event.find(params[:id])
  end


  def event_params
    params.require(:event).permit(:title, :start_time, :end_time, :location).merge(user_id: current_user.id)
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @monthly_target = MonthlyTarget.where(month_id: Date.today.month)
    # @weekly_target = WeeklyTarget.where(week_id: Date.today.cweek)
    # @daily_target = DailyTarget.where(date_id: Date.today)
    @monthly_target = MonthlyTarget.find_by(month_id: Date.today.month)
    @weekly_target = WeeklyTarget.find_by(week_id: Date.today.cweek)
    @daily_target = DailyTarget.find_by(date_id: Date.today)
  end
  

  def new
    @user_target = UserTarget.new

  end
  
  def create

    @user_target = UserTarget.new(target_params)
    @user_target.save
    redirect_to targets_path
  end
  
  def edit
 
    # @monthly_target = MonthlyTarget.where(month_id: Date.today.month)
    # @weekly_target = WeeklyTarget.where(week_id: Date.today.cweek)
    # @daily_target = DailyTarget.where(date_id: Date.today)
    @monthly_target = MonthlyTarget.find_by(month_id: Date.today.month)
    @weekly_target = WeeklyTarget.find_by(week_id: Date.today.cweek)
    @daily_target = DailyTarget.find_by(date_id: Date.today)
  end
  
  def update
    binding.pry
    # @user_target = UserTarget.find(params[:id])
    # @user_target.update(target_params) 
    
    # @monthly_target = MonthlyTarget.where(month_id: Date.today.month)
    # @weekly_target = WeeklyTarget.where(week_id: Date.today.cweek)
    # @daily_target = DailyTarget.where(date_id: Date.today)
    @monthly_target = MonthlyTarget.find_by(month_id: Date.today.month)
    @weekly_target = WeeklyTarget.find_by(week_id: Date.today.cweek)
    @daily_target = DailyTarget.find_by(date_id: Date.today)
    @monthly_target.update(target_params) 
    @weekly_target.update(target_params) 
    @daily_target.update(target_params) 
    redirect_to targets_path
  end
  

  private

  def target_params
    params.require(:user_target).permit(:monthly_content, :weekly_content, :daily_content).merge(user_id: current_user.id, date_id: Date.today, week_id: Date.today.cweek, month_id: Date.today.month)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks
  end
  
  def show
    @task = target_task params[:id]
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.new task_params
    @task.save!
    redirect_to @task
  end
  
  def edit
    @task = target_task params[:id]
  end
  
  def update
    @task = target_task params[:id]
    @task.update(task_params)
    redirect_to @task
  end
  
  def destroy
    @task = target_task params[:id]
    @task.destroy
    redirect_to tasks_url
  end
  
  private
  def target_task task_id
    current_user.tasks.where(id: task_id).take
  end
  
  def task_params
    params.require(:task).permit(:title, :description, :target_on)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :set_events_diaries

  def index

    @monthly_target = MonthlyTarget.where(user_id: current_user.id)
    @weekly_target = WeeklyTarget.where(user_id: current_user.id)
    @daily_target = DailyTarget.where(user_id: current_user.id)
    @events = Event.where(user_id: current_user.id)
    @index_events = Event.where('start_time >= ?', Date.today).order('start_time ASC').limit(5)
    @index_diaries = Diary.where('start_time <= ?', Date.today).order('start_time ASC').limit(5)
    @tasks = current_user.tasks
  end

  private

  def set_events_diaries
  @index_events = Event.where('start_time >= ?', Date.today).order('start_time ASC').limit(5)
  @index_diaries = Diary.where('start_time <= ?', Date.today).order('start_time ASC').limit(5)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/diary/_main_diary.html.erb
<div class="chat-header">
 <div class="left-header">
    <div class="header-title">

            <h1>diary</h1>      
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
 
    </div>
  </div>
</div>

<div class="calendars">
  <p id="notice"><%= notice %></p>

 


  <br>



  <%= month_calendar events: @diaries do |date, diaries| %>
    <%= date.day %>

    <% diaries.each do |diary| %>
      <div>
        
        <%= link_to diary.title, diary_path(diary.id) %> 
      </div>
    <% end %>
  <% end %>
</div>




  <%= form_with(model: @diary, url: diary_index_path, method: :post, local: true, class: 'form') do |f| %>
  <div class="diary-hed form-group" >
    <%= f.label :日付, class: 'diary-lavel' %>
    <%= f.date_field :start_time, value: Time.now.strftime("%Y-%m-%d"), class: 'date-select form-control' %>
    <%= f.label :タイトル, class: 'diary-lavel' %>
    <%= f.text_field :title, class: 'text-input form-control' %>
    <%= f.submit '保存', class: "btn btn-default form-submit" %>
  </div>

    <div class="diary-content form-group">
      <%= f.label :content, class: 'diary-lavel' %>
      <%= f.text_area :content, class: "diary-text" %>
    </div>
  <% end %>
<%#= render 'form', event: @diary %>

app/views/diary/edit.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "top/side_bar" %>
  </div>
  <div class="chat">
  
<div class="chat-header">
 <div class="left-header">
    <div class="header-title">

            <h1>diary編集</h1>      
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
 
    </div>
  </div>
</div>



  <%= form_with(model: @diary, url: diary_index_path, method: :post, local: true, class: 'form diary-edit') do |f| %>
  <div class="diary-hed form-group" >
    <%= f.label :日付, class: 'diary-lavel' %>
    <%= f.date_field :start_time, value: Time.now.strftime("%Y-%m-%d"), class: 'date-select form-control' %>
    <%= f.label :タイトル, class: 'diary-lavel' %>
    <%= f.text_field :title, class: 'text-input form-control' %>
    <%= f.submit '保存', class: "btn btn-default form-submit" %>
  </div>

    <div class="diary-content form-group">
      <%= f.label :content, class: 'diary-lavel' %>
      <%= f.text_area :content, class: "diary-text" %>
    </div>
  <% end %>


  </div>
</div>

app/views/diary/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "events/side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_diary" %>
  </div>
</div>

app/views/diary/new.html.erb
<%= form_with(model: @diary, url: diary_index_path, method: :post, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/diary/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "top/side_bar" %>
  </div>
  <div class="chat">

    <div class="chat-header">
      <div class="header-title">
        <%= @diary.title %>
      </div>  
      <div class="header-button">
        <%= link_to 'Destroy',diary_path(@diary.id), method: :delete, data: { confirm: 'Are you sure?' } %>

      </div>

    </div>
    <p id="notice"><%= notice %></p>
  <div class="diary-show-content">
    <p>
      <strong>タイトル</strong>
      <%= @diary.title %>
    </p>

    <p>
      <strong>日付</strong>
      <%= l @diary.start_time %>
    </p>

    <p>
      <strong>内容</strong>
      <%= @diary.content %>
    </p>

    <%= link_to 'Edit', edit_diary_path(@diary) %> |

    <%= link_to 'Back',  diary_index_path %>
  </div>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_main_event.html.erb
<div class="chat-header">
 <div class="left-header">
    <div class="header-title">
    <%# チャットルーム名を表示 %>
      <%# <%= @room.name %> 
          <h1>Events</h1>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <%# "チャットを終了する"をクリックすると、チャットルームが削除されるようにリンクを設定 削除のパスはroom_path 削除するチャットルームを区別するために、定義している@roomを引数にし、HTTPメソッドのdeleteを指定すると、roomsコントローラーのdestroyアクションが実行されます。 %>
      <%# <%= link_to "チャットを終了する", room_path(@room), method: :delete %> 
    </div>
  </div>
</div>


<div class="calendars">
  <p id="notice"><%= notice %></p>

  <table class=main_hed>
    <thead>
      <tr>
        <h6>直近の予定</h6>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%  @index_events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= l (event.start_time) %></td>
          <td><%= l (event.end_time) %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  

  <br>



  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>

    <% events.each do |event| %>
      <div>
        <%= link_to event.title, event_path(event.id) %>
      </div>
    <% end %>
  <% end %>
</div>








<%= form_with(model:  @event, url: events_path, method: :post, local: true, class: 'form') do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="event-content" >
    <div class="event-form form-group">
      <%= f.label :title, class: 'event-lavel', id: 'evemt-title'%>
      <%= f.text_field :title, class: 'text-input form-control' %>
    </div>
    <div class="event-form">
      <%= f.label :start_time, class: 'event-lavel' %>
      <%= f.datetime_select :start_time %>
    </div>
    <div class="event-form">
      <%= f.label :end_time, class: 'event-lavel' %>
      <%= f.datetime_select :end_time %>
    </div>
    <div class="event-form">
    <%= f.label :location, class: 'event-lavel' %>
    <%= f.text_field :location, class: 'text-input form-control'%>
    </div>
    <div class="event-form-submit">
      <%= f.submit '保存', class: "btn btn-default event-form-btn" %>
    </div>

  </div>


<% end %>

app/views/events/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "トップページ", events_path %>
  </div>
</div>


<div class="menu">

      <div class="menu-content">
        <p>  カレンダー <p>
        <p><%= link_to "diaries",  diary_index_path %><p>
        <p><%= link_to "events",   events_path %><p>
      </div>
  <div class="menu-content">
        <p><%= link_to "ToDo", tasks_path %><p>
  </div>
  <div class="menu-content">
        <p><%= link_to "目標", targets_path %><p>
  </div>
  <div class="menu-content">
    <p>直近の予定</p>
      
  </div>

  <div class="menu-content">
    <p>最近の日記</p>

  </div>



 
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "top/side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_event" %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "top/side_bar" %>
  </div>
  <div class="chat">

    <div class="chat-header">
      <div class="header-title">
        <%= @event.title %>
      </div>  
      <div class="header-button">
        <%= link_to 'Destroy', event_path(@event.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>


  <p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @event.title %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= l @event.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= l @event.end_time %>
  </p>
  <p>
    <strong>location:</strong>
    <%= @event.location %>
  </p>

  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Back', events_path %>
</div>

app/views/targets/_main_target.html.erb
<div class="chat-header">
 <div class="left-header">
    <div class="header-title">

          <h1>目標</h1>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <%# <%= link_to "新規目標", new_target_path %> %>
    <%# <%= link_to "目標設定", edit_target_path(@user_target.id, @monthly_target.id, @weekly_target.id ) %> %>
    </div>
  </div>
</div>


<div class="calendars">
  <p id="notice"><%= notice %></p>

  <table class=main_hed>
     <%= form_with(model: @user_target, url: targets_path, method: :get, local: true) do |f| %>
      <%= f.label :日付設定  %>
      <%= f.date_field :date,  value: Time.now.strftime("%Y-%m-%d")%>
      <%= f.submit '変更', class: "form-submit" %>
     <%end%>
  </table>
  

  <br>
  <div>
    <%#  @monthly_target.each do |monthly_target| %>
    <th>今月の目標</th>
    <td><%#= monthly_target.monthly_content %></td>
    <td><%= @monthly_target.monthly_content %></td>
    <td><%#= link_to 'Edit', edit_target_path(monthly_target.id) %></td>
    <td><%= link_to 'Edit', edit_target_path(@monthly_target.id) %></td>
    <% #end %>
  </div>

  <div>
    <%#  @weekly_target.each do |weekly_target| %>
    <th>今週の目標</th>
    <td><%#= weekly_target.weekly_content %></td>
    <td><%= @weekly_target.weekly_content %></td>
    <td><%#= link_to 'Edit', edit_target_path(weekly_target.id) %></td>
    <td><%= link_to 'Edit', edit_target_path(@weekly_target.id) %></td>
    <%# end %>
  </div>

  <div>
    <%# @daily_target.each do |daily_target| %>
    <th>今日の目標</th>
    <td><%#= daily_target.daily_content %></td>
    <td><%= @daily_target.daily_content %></td>
    <td><%#= link_to 'Edit', edit_target_path(daily_target.id) %></td>
    <td><%= link_to 'Edit', edit_target_path(@daily_target.id) %></td>
    <%# end %>
  </div>

  
</div>

app/views/targets/edit.html.erb
<h1>目標設定</h1>

<%= form_with(model: [@monthly_target, @weekly_target, @daily_target], target_path(@monthly_target.id, @weekly_target.id, @daily_target.id), method: :post, local: true) do |form| %>
  <%#= form_with(model: @monthly_target, local: true) do |form| %>
    <h1>月間目標</h1>
    <div class="field">
      <%= form.label :monthly_content, "月間目標" %>
      <%= form.text_field :monthly_content %>
    </div>
    <div class="actions">
      <%#= form.submit "送信" %>
    </div>
  <%# end %>

  <%#= form_with(model: @weekly_target , local: true) do |form| %>
    <h1>週間目標</h1>
    <div class="field">
    <%= form.label :weekly_content, "週間目標" %>
    <%= form.text_field :weekly_content %>
  </div>
  <div class="actions">
      <%#= form.submit "送信" %>
    </div>
  <%# end %>
  
  <%#= form_with(model: @daily_target, local: true) do |form| %>
    <h1>日間目標</h1>
    <div class="field">
      <%= form.label :daily_content, "日間目標" %>
      <%= form.text_field :daily_content %>
    </div>

    <div class="actions">
      <%= form.submit "送信" %>
    </div>
<% end %>

<%= link_to 'Back', targets_path %>

app/views/targets/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "top/side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_target" %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "top/side_bar" %>
  </div>
  <div class="chat">
    <div class="chat-header">
    <div class="left-header">
      <div class="header-title">
        <h1>ToDo</h1>
      </div>
    </div>
    <div class="right-header">
      <div class="header-button">
          <p><%= link_to 'ToDoの作成', new_task_path %></p>
      </div>
    </div>
  </div>

    <table>
      <tr>
        <h6>完了</h6><h6>/タイトル</h6><h6>/内容</h6><h6>/締め切り</h6><h6></h6><h6></h6>
      </tr>
      <% @tasks.each do |task| %>
        <div>
          <tr>
            <td><%= check_box_tag :completed %></td>
            <td><%= link_to task.title, task_path(task) %></td>
            <td><%= task.description %></td>
            <td><%= task.target_on %></td>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
        
          </tr>
        </div>
      <% end %>
    </table>

 </div>
</div>

app/views/top/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>

  <div class="create-room">
    <%= link_to "トップページ", top_index_path %>
  </div>
</div>


<div class="menu">

      <div class="menu-content">
        <p>  カレンダー <p>
        <p><%= link_to "diaries",  diary_index_path %><p>
        <p><%= link_to "events",   events_path %><p>
      </div>
  <div class="menu-content">
        <p><%= link_to "ToDo", tasks_path %><p>
  </div>
  <div class="menu-content">
        <p><%#= link_to "目標", targets_path %><p>
        <%# 後で %>
  </div>
  <div class="menu-content">
    <p>直近の予定</p>
        <% @index_events.each do |event| %>
        <p>
         <%= link_to event.title,event %>

        </p>
      <% end %>
  </div>

  <div class="menu-content">
    <p>最近の日記</p>
      <% @index_diaries.each do |diary| %>
        <p>
          <%= link_to diary.title, diary_path(diary.id) %>
        </p>
      <% end %>
  </div>



 
</div>

app/views/top/_top_page.html.erb
<div class="chat-header">
 <div class="left-header">
    <div class="header-title">

          
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <%= link_to "diary", diary_index_path %>

    </div>
  </div>
</div>


<div class="calendars">
  <p id="notice"><%= notice %></p>

  <table class=main_hed>


  </table>
  

  <br>
  <div>
    <%#  @monthly_target.each do |monthly_target| %>
    <%# <th>今月の目標</th> %>
    <td><%#= monthly_target.monthly_content %></td>
    <td><%#= link_to 'Edit', edit_target_path(monthly_target.id) %></td>
    <%# end %>
  </div>

  <div>
    <%#  @weekly_target.each do |weekly_target| %>
    <%# <th>今週の目標</th> %>
    <td><%#= weekly_target.weekly_content %></td>
    <td><%#= link_to 'Edit', edit_target_path(weekly_target.id) %></td>
    <%# end %>
  </div>

  <div>
    <%# @daily_target.each do |daily_target| %>
    <%# <th>今日の目標</th> %>
    <td><%#= daily_target.daily_content %></td>
    <td><%#= link_to 'Edit', edit_target_path(daily_target.id) %></td>
    <%# end %>
  </div>

  
  <table>
    <tr>
        <h6>完了</h6><h6>/タイトル</h6><h6>/内容</h6><h6>/締め切り</h6><h6></h6><h6></h6>
    </tr>
    <% @tasks.each do |task| %>
    
      <div>
        <tr>
          <td><%= check_box_tag :completed %></td>
          <td><%= link_to task.title, task_path(task) %></td>
          <td><%= task.description %></td>
          <td><%= task.target_on %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
      
        </tr>
      </div>
    <% end %>
  </table>

  <div class="calendars">
    <p id="notice"><%= notice %></p>

    <table class=main_hed>
      <thead>
        <tr>
          <h6>直近の予定</h6>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <%  @index_events.each do |event| %>
          <tr>
            <td><%= event.title %></td>
            <td><%= l (event.start_time) %></td>
            <td><%= l (event.end_time) %></td>
            <td><%= link_to 'Show', event %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    

    <br>



    <%= calendar(number_of_days: 3, events: @events) do | date, events | %>
    <%#= calendar events: @events do |date, events| %>
      <%= date.day %>

      <% events.each do |event| %>
        <div>
          <%= link_to event.title, event_path(event.id) %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/top/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "top_page" %>
  </div>
</div>